### ISSUE TITLE
Seems to be a typo on description

### ISSUE THREAD

**Issue by fr-sutiwo** [Polymer-Japan/lit-element-docs-jp#5]
### en
<img width="743" alt="en" src="https://user-images.githubusercontent.com/45225730/56776997-143cc780-680a-11e9-94c6-1386a29230a4.png">

https://lit-element.polymer-project.org/guide/start#setup

### ja
<img width="750" alt="ja" src="https://user-images.githubusercontent.com/45225730/56776998-14d55e00-680a-11e9-87c6-9393d151e2bc.png">

https://lit-element.polymer-jp.org/guide/start#%E5%89%8D%E6%BA%96%E5%82%99

#### Live Demo

https://stackblitz.com/edit/lit-element-example?file=index.js

https://glitch.com/edit/#!/hello-lit-element?path=index.html:1:0

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: vX.X.X
- webcomponents: vX.X.X

**Comment by sizuhiko** [comment]
I confirmed fixed japanese document.
